# Generated by Django 5.2.5 on 2025-09-18 03:31

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='cancha',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='reserva',
        ),
        migrations.AlterModelOptions(
            name='cancha',
            options={'ordering': ('recinto__nombre', 'nombre'), 'verbose_name': 'Cancha', 'verbose_name_plural': 'Canchas'},
        ),
        migrations.AlterModelOptions(
            name='recinto',
            options={'ordering': ('nombre',), 'verbose_name': 'Recinto', 'verbose_name_plural': 'Recintos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ('-fecha_hora_inicio',), 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='cancha',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancha',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='duracion_tramo_min',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='cancha',
            name='tipo_superficie',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='recinto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recinto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recinto',
            name='comuna',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recinto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recinto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='recinto',
            name='hora_apertura',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='recinto',
            name='hora_cierre',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AddField(
            model_name='recinto',
            name='url_maps',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_hora_fin',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 4, 28, 19, 118366, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_hora_inicio',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 18, 3, 31, 15, 952226, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='deporte',
            field=models.CharField(choices=[('FUTBOL', 'Fútbol'), ('TENIS', 'Tenis'), ('PADEL', 'Pádel'), ('MULTI', 'Multicancha'), ('OTRO', 'Otro')], default='FUTBOL', max_length=12),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='telefono',
            field=models.CharField(blank=True, default=datetime.datetime(2025, 9, 18, 3, 31, 37, 766111, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.cancha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('NO_SHOW', 'No show')], default='PENDIENTE', max_length=12),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cancha',
            unique_together={('recinto', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cancha', 'fecha_hora_inicio'], name='core_reserv_cancha__2ac941_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cancha', 'fecha_hora_fin'], name='core_reserv_cancha__0dd025_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='core_reserv_estado_eb5fb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_hora_fin__gt', models.F('fecha_hora_inicio'))), name='reserva_fin_mayor_que_inicio'),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
