# Generated by Django 5.2.6 on 2025-10-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carrito_reservatemporal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'ordering': ('-creado_en',), 'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
        migrations.AlterModelOptions(
            name='reservatemporal',
            options={'ordering': ('-creado_en',), 'verbose_name': 'Reserva temporal', 'verbose_name_plural': 'Reservas temporales'},
        ),
    ]
