# Generated by Django 5.2.6 on 2025-10-08 03:01

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_carrito_options_alter_reservatemporal_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservatemporal',
            name='expira_en',
            field=models.DateTimeField(default=core.models.default_expiry),
        ),
        migrations.AddIndex(
            model_name='carrito',
            index=models.Index(fields=['usuario', 'pagado'], name='core_carrit_usuario_15c339_idx'),
        ),
        migrations.AddIndex(
            model_name='reservatemporal',
            index=models.Index(fields=['carrito', 'pagada'], name='core_reserv_carrito_207973_idx'),
        ),
        migrations.AddIndex(
            model_name='reservatemporal',
            index=models.Index(fields=['expira_en'], name='core_reserv_expira__8fd78d_idx'),
        ),
    ]
