# Generated by Django 5.2.6 on 2025-10-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservatemporal_usuario'),
        ('core', '0005_alter_carrito_usuario_and_more'),
    ]

    operations = [
    ]
