# Generated by Django 5.2.6 on 2025-10-15 19:43

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251013_1216'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="reservatemporal",
                    name="usuario",
                    field=models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas_temporales",
                        db_column="usuario_id",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
