# Generated by Django 5.2.6 on 2025-10-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_reservatemporal_usuario_and_more'),
    ]

    operations = [
    ]
