# Generated by Django 5.2.6 on 2025-10-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_backfill_reservatemporal_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recinto',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
