# Generated by Django 5.2.6 on 2025-11-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_recinto_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud en formato decimal, ej: -33.448890', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cancha',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud en formato decimal, ej: -70.669265', max_digits=9, null=True),
        ),
    ]
